from .Trabajador import Trabajador
from .User import CustomUser
from .CategoriaCurso import CategoriaCurso
from .Curso import Curso    
from .Certificado import Certificado
from .CategoriaCertificado import CategoriaCertificado
from .Especialidad import Especialidad
from .EspecialidadImagen import EspecialidadImagen
from .CategoriaEspecialidad import CategoriaEspecialidad