# Generated by Django 6.0.1 on 2026-03-10 14:58

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCertificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaCertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese la categoria de certificado', max_length=150, verbose_name='Categoria de certificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_certificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaEspecialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_especialidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaEstudioNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_estudio_nave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de estudio',
                'verbose_name_plural': 'Categorias de estudios',
            },
        ),
        migrations.CreateModel(
            name='CategoriaNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese la categoria de nave', max_length=150, verbose_name='Categoria de nave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de nave',
                'verbose_name_plural': 'Categorias de naves',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_permiso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaPirotecnia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese el tipo de bengala', max_length=150, verbose_name='Tipo de bengala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_pirotecnia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaTitulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_titulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.categoriacertificado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='certificados/imagenes/')),
                ('tipo', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('extra', 'Extra')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_certificado', to='aplication.certificado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de certificado',
                'verbose_name_plural': 'Imágenes de certificados',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='aplication.categoriaespecialidad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='especialidades/imagenes/')),
                ('tipo', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('extra', 'Extra')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_especialidad', to='aplication.especialidad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_especialidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de especialidad',
                'verbose_name_plural': 'Imágenes de especialidades',
            },
        ),
        migrations.CreateModel(
            name='Naves',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese el nombre', max_length=150, unique=True, verbose_name='Nombre')),
                ('sllamada', models.CharField(help_text='Ingrese la señal de llamada', max_length=17, unique=True, verbose_name='Señal de llamada')),
                ('matricula', models.CharField(help_text='Ingrese la matricula', max_length=17, unique=True, verbose_name='Matricula')),
                ('eslora', models.FloatField(help_text='Ingrese la eslora', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Eslora')),
                ('manga', models.FloatField(help_text='Ingrese la manga', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Manga')),
                ('puntal', models.FloatField(help_text='Ingrese el puntal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Puntal')),
                ('trg', models.FloatField(help_text='Ingrese el trg', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Trg')),
                ('tminima', models.IntegerField(help_text='Ingrese la dotacion minima', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Dotacion minima')),
                ('tmaxima', models.IntegerField(help_text='Ingrese la capacidad maxima de personas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Cap. max de personas')),
                ('pasajeros', models.IntegerField(help_text='Ingrese la capacidad de pasajeros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Cap. de pasajeros')),
                ('actividad', models.CharField(error_messages={'required': 'El campo %(field_label)s es obligatorio y no puede contener solo espacios en blanco.'}, help_text='Ingrese la actividad de la nave.', max_length=150, verbose_name='Actividad de la nave')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='archivos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naves', to='aplication.categorianave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nave',
                'verbose_name_plural': 'Naves',
            },
        ),
        migrations.CreateModel(
            name='EstudioNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='aplication.categoriaestudionave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudios_naves', to=settings.AUTH_USER_MODEL)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='aplication.naves')),
            ],
            options={
                'verbose_name': 'Estudio de nave',
                'verbose_name_plural': 'Estudios de naves',
            },
        ),
        migrations.CreateModel(
            name='CertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, help_text='Ingrese la fecha de emision', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 10), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha emision')),
                ('fecha_vigencia', models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 10), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha expiracion')),
                ('observacion', models.CharField(blank=True, default='', help_text='Ingrese alguna observacion al certificado', max_length=150, null=True, verbose_name='Observacion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriacertificadonave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_naves', to=settings.AUTH_USER_MODEL)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.naves')),
            ],
            options={
                'verbose_name': 'Certificado de la nave',
                'verbose_name_plural': 'Certificados de las naves',
            },
        ),
        migrations.CreateModel(
            name='PirotecniaNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad de bengala', validators=[django.core.validators.MinValueValidator(1, message='El cantidad debe ser mayor que %(limit_value)s.'), django.core.validators.MaxValueValidator(20, message='La cantidad debe ser menor o igual a 20.')], verbose_name='Cantidad de bengala')),
                ('fecha_vigencia', models.DateField(help_text='Ingrese la fecha de expiracion de la bengala', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 10), message='La fecha de vencimiento no puede ser anterior a 3 años de la fecha actual'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2036, 3, 10), message='La fecha de vencimiento no puede ser posterior a 10 años a partir de la fecha actual.')], verbose_name='Fecha expiracion')),
                ('observacion', models.CharField(blank=True, default='', help_text='Ingrese observacion de la bengala', max_length=150, null=True, verbose_name='Observacion de la bengala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriapirotecnia')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirotecnias', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pirotecnias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('output_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Peso del archivo en bytes', null=True)),
                ('file_path', models.TextField(help_text='Ruta o URL donde quedó almacenado el archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('residencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de residencia')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='especialidad',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='aplication.trabajador'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.trabajador'),
        ),
        migrations.CreateModel(
            name='RequisitoCertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligatorio', models.BooleanField(default=True)),
                ('aplica_a_todas', models.BooleanField(default=True, help_text='Si aplica a todas las naves')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_certificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriacertificadonave', verbose_name='Tipo de certificado')),
                ('naves', models.ManyToManyField(blank=True, related_name='requisitos_especificos', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisito de certificado',
                'verbose_name_plural': 'Requisitos de certificados',
                'unique_together': {('categoria_certificado',)},
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='aplication.categoriatitulo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='aplication.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='aplication.categoriapermiso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='aplication.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='especialidad',
            unique_together={('trabajador', 'categoria')},
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=2)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplication.categoriacurso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplication.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('trabajador', 'categoria')},
        ),
    ]
