# Generated by Django 6.0.1 on 2026-03-23 15:35

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de emision', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 23), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha emision'),
        ),
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 23), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha expiracion'),
        ),
        migrations.AlterField(
            model_name='pirotecnianave',
            name='fecha_vigencia',
            field=models.DateField(help_text='Ingrese la fecha de expiracion de la bengala', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 23), message='La fecha de vencimiento no puede ser anterior a 3 años de la fecha actual'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2036, 3, 23), message='La fecha de vencimiento no puede ser posterior a 10 años a partir de la fecha actual.')], verbose_name='Fecha expiracion'),
        ),
        migrations.CreateModel(
            name='DetalleEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_total_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplication.estudionave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_estudios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
