# Generated by Django 6.0.1 on 2026-01-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_cargo_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='aplication.cargo'),
        ),
    ]
