# Generated by Django 6.0.1 on 2026-01-16 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_remove_trabajador_cargo_trabajador_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaTrabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='matriculas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='aplication.trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='matriculas/imagenes/')),
                ('tipo', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('extra', 'Extra')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_matriculas', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='aplication.matriculatrabajador')),
            ],
            options={
                'verbose_name': 'Imagen de matrícula',
                'verbose_name_plural': 'Imágenes de matrículas',
            },
        ),
        migrations.CreateModel(
            name='TipoMatricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese el tipo de matricula', max_length=150, verbose_name='Tipo matricula')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Ingrese descripcion del tipo de matricula', max_length=150, null=True, verbose_name='Descripcion del tipo de matricula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de matricula',
                'verbose_name_plural': 'Tipos de matriculas',
            },
        ),
        migrations.AddField(
            model_name='matriculatrabajador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='aplication.tipomatricula'),
        ),
    ]
