# Generated by Django 6.0.1 on 2026-01-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_matriculatrabajador_matriculaimagen_tipomatricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculatrabajador',
            name='archivo',
        ),
    ]
