# Generated by Django 6.0.1 on 2026-01-19 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_remove_matriculatrabajador_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='matriculaimagen',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='matriculaimagen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matriculatrabajador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='matriculatrabajador',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='matriculatrabajador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tipomatricula',
            name='user',
        ),
        migrations.CreateModel(
            name='CategoriaCertificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaEspecialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.categoriacertificado')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=2)),
                ('fecha_vigencia', models.DateField()),
                ('categoria_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplication.categoriacurso')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplication.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'categoria_curso')},
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='aplication.categoriaespecialidad')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='aplication.trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='EspecialidadImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='especialidades/imagenes/')),
                ('tipo', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('extra', 'Extra')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_especialidad', to='aplication.especialidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_especialidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de especialidad',
                'verbose_name_plural': 'Imágenes de especialidades',
            },
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='MatriculaImagen',
        ),
        migrations.DeleteModel(
            name='MatriculaTrabajador',
        ),
        migrations.DeleteModel(
            name='TipoMatricula',
        ),
    ]
