# Generated by Django 6.0.1 on 2026-01-19 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_remove_trabajador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacertificado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_certificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriacurso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaespecialidad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_especialidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='especialidadimagen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_especialidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
