# Generated by Django 6.0.1 on 2026-01-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_categoriacertificado_user_categoriacurso_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='categoria_curso',
            new_name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('trabajador', 'categoria')},
        ),
    ]
