# Generated by Django 6.0.1 on 2026-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_rename_categoria_curso_curso_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
