# Generated by Django 6.0.1 on 2026-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0009_alter_certificado_fecha_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
