# Generated by Django 6.0.1 on 2026-01-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_trabajador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
