# Generated by Django 6.0.1 on 2026-01-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0011_alter_especialidad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacertificado',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categoriacurso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categoriaespecialidad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
