# Generated by Django 6.0.1 on 2026-01-27 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0013_processedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='certificados/imagenes/')),
                ('tipo', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('extra', 'Extra')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_certificado', to='aplication.certificado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de certificado',
                'verbose_name_plural': 'Imágenes de certificados',
            },
        ),
    ]
