# Generated by Django 6.0.1 on 2026-01-29 14:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0014_certificadoimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese la categoria de certificado', max_length=150, verbose_name='Categoria de certificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_certificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese la categoria de nave', max_length=150, verbose_name='Categoria de nave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de nave',
                'verbose_name_plural': 'Categorias de naves',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPirotecnia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese el tipo de bengala', max_length=150, verbose_name='Tipo de bengala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_pirotecnia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Naves',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', help_text='Ingrese el nombre', max_length=150, unique=True, verbose_name='Nombre')),
                ('sllamada', models.CharField(help_text='Ingrese la señal de llamada', max_length=17, unique=True, verbose_name='Señal de llamada')),
                ('matricula', models.CharField(help_text='Ingrese la matricula', max_length=17, unique=True, verbose_name='Matricula')),
                ('eslora', models.FloatField(help_text='Ingrese la eslora', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Eslora')),
                ('manga', models.FloatField(help_text='Ingrese la manga', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Manga')),
                ('puntal', models.FloatField(help_text='Ingrese el puntal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Puntal')),
                ('trg', models.FloatField(help_text='Ingrese el trg', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Trg')),
                ('tminima', models.IntegerField(help_text='Ingrese la dotacion minima', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Dotacion minima')),
                ('tmaxima', models.IntegerField(help_text='Ingrese la capacidad maxima de personas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Cap. max de personas')),
                ('pasajeros', models.IntegerField(help_text='Ingrese la capacidad de pasajeros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Cap. de pasajeros')),
                ('actividad', models.CharField(error_messages={'required': 'El campo %(field_label)s es obligatorio y no puede contener solo espacios en blanco.'}, help_text='Ingrese la actividad de la nave.', max_length=150, verbose_name='Actividad de la nave')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='archivos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naves', to='aplication.categorianave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nave',
                'verbose_name_plural': 'Naves',
            },
        ),
        migrations.CreateModel(
            name='CertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, help_text='Ingrese la fecha de emision', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 1, 29), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha emision')),
                ('fecha_vigencia', models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 1, 29), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha expiracion')),
                ('observacion', models.CharField(blank=True, default='', help_text='Ingrese alguna observacion al certificado', max_length=150, null=True, verbose_name='Observacion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriacertificadonave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_naves', to=settings.AUTH_USER_MODEL)),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aplication.naves')),
            ],
            options={
                'verbose_name': 'Certificado de la nave',
                'verbose_name_plural': 'Certificados de las naves',
            },
        ),
        migrations.CreateModel(
            name='Pirotecnia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad de bengala', validators=[django.core.validators.MinValueValidator(1, message='El cantidad debe ser mayor que %(limit_value)s.'), django.core.validators.MaxValueValidator(20, message='La cantidad debe ser menor o igual a 20.')], verbose_name='Cantidad de bengala')),
                ('fecha_vigencia', models.DateField(help_text='Ingrese la fecha de expiracion de la bengala', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 1, 29), message='La fecha de vencimiento no puede ser anterior a 3 años de la fecha actual'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2036, 1, 29), message='La fecha de vencimiento no puede ser posterior a 10 años a partir de la fecha actual.')], verbose_name='Fecha expiracion')),
                ('observacion', models.CharField(blank=True, default='', help_text='Ingrese observacion de la bengala', max_length=150, null=True, verbose_name='Observacion de la bengala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriapirotecnia')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirotecnias', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pirotecnias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoCertificadoNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligatorio', models.BooleanField(default=True)),
                ('aplica_a_todas', models.BooleanField(default=True, help_text='Si aplica a todas las naves de esta categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_certificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriacertificadonave', verbose_name='Tipo de certificado')),
                ('categoria_nave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categorianave', verbose_name='Categoría de nave')),
                ('naves', models.ManyToManyField(blank=True, related_name='requisitos_especificos', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisito de certificado',
                'verbose_name_plural': 'Requisitos de certificados',
                'unique_together': {('categoria_certificado', 'categoria_nave')},
            },
        ),
    ]
