# Generated by Django 6.0.1 on 2026-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0015_categoriacertificadonave_categorianave_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requisitocertificadonave',
            unique_together={('categoria_certificado',)},
        ),
        migrations.AlterField(
            model_name='requisitocertificadonave',
            name='aplica_a_todas',
            field=models.BooleanField(default=True, help_text='Si aplica a todas las naves'),
        ),
        migrations.RemoveField(
            model_name='requisitocertificadonave',
            name='categoria_nave',
        ),
    ]
