# Generated by Django 6.0.1 on 2026-02-06 19:02

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0016_alter_requisitocertificadonave_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de emision', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 6), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha emision'),
        ),
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 6), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha expiracion'),
        ),
        migrations.AlterField(
            model_name='pirotecnia',
            name='fecha_vigencia',
            field=models.DateField(help_text='Ingrese la fecha de expiracion de la bengala', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 2, 6), message='La fecha de vencimiento no puede ser anterior a 3 años de la fecha actual'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2036, 2, 6), message='La fecha de vencimiento no puede ser posterior a 10 años a partir de la fecha actual.')], verbose_name='Fecha expiracion'),
        ),
        migrations.CreateModel(
            name='CategoriaTitulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_titulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='aplication.categoriatitulo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='aplication.trabajador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='aplication.categoriatitulo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='aplication.trabajador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trabajador', 'categoria')},
            },
        ),
    ]
