# Generated by Django 6.0.1 on 2026-02-06 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0017_alter_certificadonave_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_permiso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('codigo', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='permiso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='aplication.categoriapermiso'),
        ),
    ]
