# Generated by Django 6.0.1 on 2026-02-10 14:42

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0018_categoriapermiso_alter_permiso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de emision', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 10), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha emision'),
        ),
        migrations.AlterField(
            model_name='certificadonave',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 10), message='La fecha de vencimiento no puede ser anterior a 1 año de la fecha actual')], verbose_name='Fecha expiracion'),
        ),
        migrations.CreateModel(
            name='PirotecniaNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad de bengala', validators=[django.core.validators.MinValueValidator(1, message='El cantidad debe ser mayor que %(limit_value)s.'), django.core.validators.MaxValueValidator(20, message='La cantidad debe ser menor o igual a 20.')], verbose_name='Cantidad de bengala')),
                ('fecha_vigencia', models.DateField(help_text='Ingrese la fecha de expiracion de la bengala', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 2, 10), message='La fecha de vencimiento no puede ser anterior a 3 años de la fecha actual'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2036, 2, 10), message='La fecha de vencimiento no puede ser posterior a 10 años a partir de la fecha actual.')], verbose_name='Fecha expiracion')),
                ('observacion', models.CharField(blank=True, default='', help_text='Ingrese observacion de la bengala', max_length=150, null=True, verbose_name='Observacion de la bengala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.categoriapirotecnia')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirotecnias', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pirotecnias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pirotecnia',
        ),
    ]
