# Generated by Django 6.0.1 on 2026-02-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0019_alter_certificadonave_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstudioNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_estudio_nave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de estudio',
                'verbose_name_plural': 'Categorias de estudios',
            },
        ),
        migrations.CreateModel(
            name='EstudioNave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='aplication.categoriaestudionave')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='aplication.naves')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudios_naves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio de nave',
                'verbose_name_plural': 'Estudios de naves',
            },
        ),
    ]
